spring.application.name=LlamaPayTf
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/LlamapayPrueba2
spring.datasource.username=postgres
spring.datasource.password=laky4ever
server.port=8085
